name: 部署测试
on:
  push:
    branches:
      - vitepress-dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16.19.0"
      - name: create env file
        run: |
          touch .env
          echo VITE_CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo VITE_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
      - name: install and build
        run: |
          yarn install
          yarn build
      - name: 部署到 github-page...
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: docs/.vitepress/dist
