name: 部署测试
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20.6.0"
      - name: create env file
        run: |
          touch .env
          echo VITE_CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo VITE_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
      - name: install and build
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install
          pnpm build
      - name: 部署到 github-page...
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: docs/.vitepress/dist
          clean: true
          clean-exclude: |
            .env
